"""added enum types for post reaction

Revision ID: ce4fae2a90d0
Revises: e97927f49218
Create Date: 2025-10-02 13:20:54.369574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4fae2a90d0'
down_revision: Union[str, Sequence[str], None] = 'e97927f49218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = sa.Enum(
        "PENDING", "ACCEPTED", "REJECTED", "BLOCKED", name="friendshipstatus"
    )
    enum_type.create(op.get_bind())

    # Затем меняем тип колонки
    op.alter_column(
        "friendship",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=enum_type,
        existing_nullable=True,
        postgresql_using="CASE WHEN status = 'requested' THEN 'PENDING'::friendshipstatus "
                                "ELSE status::friendshipstatus END"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendship', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='friendshipstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS friendshipstatus;")
